version: '3.8'
services:
  metabase_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      METABASE_PASSWORD: password
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/postgres/:/docker-entrypoint-initdb.d/
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3005:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5435
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: host.docker.internal
      MB_ENCRYPTION_SECRET_KEY: qwertyqwertyqwerty
    volumes:
      - mb_data:/metabase-data
    depends_on:
      - metabase_db
volumes:
  postgres_data:
  mb_data:
